routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});

Route::get('/', 'FrontendController@homepage')->name('homepage');
Route::get('/collections', 'FrontendController@collections')->name('collections');
Route::get('/wallpapers', 'FrontendController@wallpapers')->name('wallpapers');

Auth::routes();

/*
|--------------------------------------------------------------------------
| Backend routes
|--------------------------------------------------------------------------
*/
Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    /*
  |--------------------------------------------------------------------------
  | Settings Routes
  |--------------------------------------------------------------------------
  */
    Route::group([ 'as' => 'setting.', 'prefix' => 'setting' ], function () {
        Route::get('', 'SettingController@index')->name('index');
        Route::put('update', 'SettingController@update')->name('update');
    });

    /*
   |--------------------------------------------------------------------------
   | Menu CRUD Routes
   |--------------------------------------------------------------------------
   */
    Route::group([ 'as' => 'wallpaper.', 'prefix' => 'wallpaper' ], function () {
        Route::get('', 'WallpaperController@index')->name('index');
        Route::get('create-wallpaper', 'WallpaperController@create')->name('create');
        Route::post('', 'WallpaperController@store')->name('store');
        Route::get('{wallpaper}/edit', 'WallpaperController@edit')->name('edit');
        Route::put('{wallpaper}', 'WallpaperController@update')->name('update');
        Route::delete('{wallpaper}', 'WallpaperController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'collection.', 'prefix' => 'collection' ], function () {
        Route::get('', 'CollectionController@index')->name('index');
        Route::get('create-collection', 'CollectionController@create')->name('create');
        Route::post('', 'CollectionController@store')->name('store');
        Route::get('{collection}/edit', 'CollectionController@edit')->name('edit');
        Route::put('{collection}', 'CollectionController@update')->name('update');
        Route::delete('{collection}', 'CollectionController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'tag.', 'prefix' => 'tag' ], function () {
        Route::get('', 'TagController@index')->name('index');
        Route::post('', 'TagController@store')->name('store');
        Route::get('{tag}/edit', 'TagController@edit')->name('edit');
        Route::put('{tag}', 'TagController@update')->name('update');
        Route::delete('{tag}', 'TagController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'category.', 'prefix' => 'category' ], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::post('', 'CategoryController@store')->name('store');
        Route::get('{category}/edit', 'CategoryController@edit')->name('edit');
        Route::put('{category}', 'CategoryController@update')->name('update');
        Route::delete('{category}', 'CategoryController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'img.', 'prefix' => 'image' ], function () {
        Route::get('', 'ImgController@index')->name('index');
        Route::get('create-img', 'ImgController@create')->name('create');
        Route::post('', 'ImgController@store')->name('store');
        Route::get('{img}/edit', 'ImgController@edit')->name('edit');
        Route::put('{img}', 'ImgController@update')->name('update');
        Route::delete('{img}', 'ImgController@destroy')->name('destroy');
    });

});

app/Models/Img.php
<?php

namespace App\Models;

use App\Models\Tag;
use Illuminate\Database\Eloquent\Model;

class Img extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'is_published',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = $value;

        if (!$this->exists) {
            $this->setUniqueSlug($value, '');
        }
    }

    protected function setUniqueSlug($name, $extra)
    {
        $slug = str_slug($name . '_' . $extra);

        if (static::whereSlug($slug)->exists()) {
            $this->setUniqueSlug($name, $extra + 1);

            return;
        }

        $this->attributes['slug'] = $slug;
    }

    public function tag()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }
}

app/Http/Controllers/ImgController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreImg;
use App\Http\Requests\UpdateImg;
use App\Models\Img;
use App\Models\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ImgController extends Controller
{
    public function index()
    {
        $img = Img::orderBy('id', 'ASC')->get();

        return view('backend.img.index', compact('img'));
    }

    public function create()
    {
        $tags = Tag::all()->pluck('name','id');

        return view('backend.img.create',compact('tags'));
    }

    public function store(StoreImg $request)
    {
        DB::transaction(function () use ($request) {
            $data = $request->data();

            $img = Img::create($data);
            foreach($request->tag as $tags){
                $pivotimgs = $img->tag()->attach($tags);
            }
            $this->uploadRequestImage($request, $img);
        });

        return redirect()->route('img.index')->withSuccess(trans('Img has been added successfully', [ 'entity' => 'Img' ]));
    }

    public function edit(Img $img)
    {
        return view('backend.img.edit', compact('img'));
    }

    public function update(UpdateImg $request, Img $img)
    {
        DB::transaction(function () use ($request, $img) {

            $data = $request->data();

            $img->update($data);

            if ($request->image)
            {
                $this->uploadRequestImage($request, $img);
            }
        });

        return redirect()->route('img.index')->with('success', 'Image has been updated', ['entity'=>'Img']);
    }


    public function destroy(Img $img)
    {
        $img->delete();

        return back()->with('success', 'Image has been deleted');
    }
}

resources/views/backend/img/partials/form.blade.php
<div class="row">
    <div class="col-md-12">
    {{--<!-- @include('partials.errors') -->--}}
    </div>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-head">
                <header>{!! $header !!}</header>
                <div class="tools visible-xs">
                    <a class="btn btn-default btn-ink" href="{{ route('img.index') }}">
                        <i class="md md-arrow-back"></i>
                        Back
                    </a>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="Publish">
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            {{ Form::text('name',old('name'),['class'=>'form-control', 'required']) }}
                            {{ Form::label('name','Name*') }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <label class="text-default-light">Featured Image</label>
                        @if(isset($img) && $img->image)
                            <input type="file" name="image" class="dropify" data-default-file="{{ asset($img->image->path) }}"/>
                        @else
                            <input type="file" name="image" class="dropify"/>
                        @endif
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <select class="form-control select2-list" name="tag[]" multiple="multiple" id="img_tag">
                                <option value="">Select Tags</option>
                                @foreach($tags as $key => $tag)
                                    <option value="{{$key}}"
                                            @if(isset($img->tag_id) ? $img->tag_id == $key : null) selected="selected" @endif>{{$tag}}</option>
                                @endforeach
                            </select>
                            {{ Form::label('tag', 'tags') }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-actionbar">
                <div class="card-actionbar-row">
                    <button type="reset" class="btn btn-default ink-reaction">Reset</button>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($img) && $img->is_published ? 'Save' : 'Publish' }}">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card card-affix affix-4">
            <div class="card-head">
                <div class="tools">
                    <a class="btn btn-default btn-ink" href="{{ route('img.index') }}">
                        <i class="md md-arrow-back"></i>
                        Back
                    </a>
                </div>
            </div>
            <div class="card-actionbar">
                <div class="card-actionbar-row">
                    <button type="reset" class="btn btn-default ink-reaction">Reset</button>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($img) && $img->is_published ? 'Save' : 'Publish' }}">
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(document).ready(function () {
            $('#img_tag').select2();
        })
    </script>
@endpush

resources/views/backend/img/partials/tables.blade.php
<tr>
    <td>{{++$key}}</td>
    <td>{{ str_limit($img->name, 47) }}</td>
    <td class="text-center">
        @if ($img->is_published == '1' )
            <span class="label label-success">{{ $img->is_published ? 'Yes' : 'No' }}</span>
        @elseif( $img->is_published  == '0' )
            <span class="label label-warning">{{ $img->is_published ? 'Yes' : 'No' }}</span>
        @endif
    </td>
    <td class="text-right">
        <button type="button" data-url="{{ route('img.destroy', $img->slug) }}" class="btn btn-flat btn-primary btn-xs item-delete">
            Delete
        </button>
        <a href="{{route('img.edit', $img->slug)}}" class="btn btn-flat btn-primary btn-xs">
            Edit
        </a>
    </td>
</tr>