routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});

Route::get('/', 'FrontendController@homepage')->name('homepage');
Route::get('/collections', 'FrontendController@collections')->name('collections');
Route::get('/wallpapers', 'FrontendController@wallpapers')->name('wallpapers');

Auth::routes();

/*
|--------------------------------------------------------------------------
| Backend routes
|--------------------------------------------------------------------------
*/
Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    /*
  |--------------------------------------------------------------------------
  | Settings Routes
  |--------------------------------------------------------------------------
  */
    Route::group([ 'as' => 'setting.', 'prefix' => 'setting' ], function () {
        Route::get('', 'SettingController@index')->name('index');
        Route::put('update', 'SettingController@update')->name('update');
    });

    /*
   |--------------------------------------------------------------------------
   | Menu CRUD Routes
   |--------------------------------------------------------------------------
   */
    Route::group([ 'as' => 'wallpaper.', 'prefix' => 'wallpaper' ], function () {
        Route::get('', 'WallpaperController@index')->name('index');
        Route::get('create-wallpaper', 'WallpaperController@create')->name('create');
        Route::post('', 'WallpaperController@store')->name('store');
        Route::get('{wallpaper}/edit', 'WallpaperController@edit')->name('edit');
        Route::put('{wallpaper}', 'WallpaperController@update')->name('update');
        Route::delete('{wallpaper}', 'WallpaperController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'collection.', 'prefix' => 'collection' ], function () {
        Route::get('', 'CollectionController@index')->name('index');
        Route::get('create-collection', 'CollectionController@create')->name('create');
        Route::post('', 'CollectionController@store')->name('store');
        Route::get('{collection}/edit', 'CollectionController@edit')->name('edit');
        Route::put('{collection}', 'CollectionController@update')->name('update');
        Route::delete('{collection}', 'CollectionController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'tag.', 'prefix' => 'tag' ], function () {
        Route::get('', 'TagController@index')->name('index');
        Route::post('', 'TagController@store')->name('store');
        Route::get('{tag}/edit', 'TagController@edit')->name('edit');
        Route::put('{tag}', 'TagController@update')->name('update');
        Route::delete('{tag}', 'TagController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'category.', 'prefix' => 'category' ], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::post('', 'CategoryController@store')->name('store');
        Route::get('{category}/edit', 'CategoryController@edit')->name('edit');
        Route::put('{category}', 'CategoryController@update')->name('update');
        Route::delete('{category}', 'CategoryController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'img.', 'prefix' => 'image' ], function () {
        Route::get('', 'ImgController@index')->name('index');
        Route::get('create-img', 'ImgController@create')->name('create');
        Route::post('', 'ImgController@store')->name('store');
        Route::get('{img}/edit', 'ImgController@edit')->name('edit');
        Route::put('{img}', 'ImgController@update')->name('update');
        Route::delete('{img}', 'ImgController@destroy')->name('destroy');
    });

});

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Wallpaper;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'is_published',
        'is_primary',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = $value;

        if (!$this->exists) {
            $this->setUniqueSlug($value, '');
        }
    }

    protected function setUniqueSlug($name, $extra)
    {
        $slug = str_slug($name . '_' . $extra);

        if (static::whereSlug($slug)->exists()) {
            $this->setUniqueSlug($name, $extra + 1);

            return;
        }

        $this->attributes['slug'] = $slug;
    }

    public function wallpaper()
    {
        return $this->belongsToMany(Wallpaper::class);
    }


}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreCategory;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    public function index()
    {
        $category = Category::orderBy('id', 'ASC')->get();

        return view('backend.category.index', compact('category'));
    }

    public function store(StoreCategory $request)
    {
        DB::transaction(function () use ($request) {

            $data = $request->data();

            $category = Category::create($data);

            $this->uploadRequestImage($request, $category);
        });

        return redirect()->route('category.index')->withSuccess(trans('Category has been added successfully', [ 'entity' => 'Category' ]));
    }

    public function edit(Category $category)
    {
        return view('backend.category.edit', compact('category'));
    }

    public function update(UpdateCategory $request, Category $category)
    {
        DB::transaction(function () use ($request, $category) {

            $data = $request->data();

            $category->update($data);

            if ($request->image)
            {
                $this->uploadRequestImage($request, $category);
            }
        });


        return redirect()->route('category.index')->with('success', 'Category has been updated', [ 'entity' => 'Category' ]);
    }


    public function destroy(Category $category)
    {
        $category->delete();

        return back()->with('success', 'category has been deleted');
    }
}

resources/views/backend/Category/partials/addCategoryModal.blade.php
<div class="modal fade" id="addCategory" tabindex="-1" role="dialog" aria-labelledby="addCategoryLabel">
    {{ Form::open(['route' => 'category.store', 'class' => 'form']) }}
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="addCategoryLabel">Add Category</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    {{ Form::text('name', old('name'), ['class' => 'form-control']) }}
                    <label class="name">Name</label>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($tag) && $tag->is_published ? 'Save' : 'Publish' }}">
            </div>
        </div>
    </div>
    {{ Form::close() }}
</div>

resources/views/backend/Category/partials/tables.blade.php
<tr>
    <td>{{++$key}}</td>
    <td>{{ str_limit($category->name, 47) }}</td>
    <td class="text-center">
        @if ($category->is_published == '1' )
            <span class="label label-success">{{ $category->is_published ? 'Yes' : 'No' }}</span>
        @elseif( $category->is_published  == '0' )
            <span class="label label-warning">{{ $category->is_published ? 'Yes' : 'No' }}</span>
        @endif
    </td>
    <td class="text-right">
        <button type="button" data-url="{{ route('category.destroy', $category->slug) }}" class="btn btn-flat btn-primary btn-xs item-delete">
            Delete
        </button>
        <a href="{{route('tag.edit', $category->slug)}}" class="btn btn-flat btn-primary btn-xs">
            Edit
        </a>
        {{--<button class="btn btn-flat btn-primary btn-xs" data-toggle="modal" data-target="#addTag" type="button">--}}
            {{--Edit--}}
        {{--</button>--}}
    </td>
</tr>