routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.homepage');
});

Route::get('/', 'FrontendController@homepage')->name('homepage');
Route::get('/collections', 'FrontendController@collections')->name('collections');
Route::get('/wallpapers', 'FrontendController@wallpapers')->name('wallpapers');

Auth::routes();

/*
|--------------------------------------------------------------------------
| Backend routes
|--------------------------------------------------------------------------
*/
Route::group([ 'prefix' => 'backend', 'middleware' => 'auth' ], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    /*
  |--------------------------------------------------------------------------
  | Settings Routes
  |--------------------------------------------------------------------------
  */
    Route::group([ 'as' => 'setting.', 'prefix' => 'setting' ], function () {
        Route::get('', 'SettingController@index')->name('index');
        Route::put('update', 'SettingController@update')->name('update');
    });

    /*
   |--------------------------------------------------------------------------
   | Menu CRUD Routes
   |--------------------------------------------------------------------------
   */
    Route::group([ 'as' => 'wallpaper.', 'prefix' => 'wallpaper' ], function () {
        Route::get('', 'WallpaperController@index')->name('index');
        Route::get('create-wallpaper', 'WallpaperController@create')->name('create');
        Route::post('', 'WallpaperController@store')->name('store');
        Route::get('{wallpaper}/edit', 'WallpaperController@edit')->name('edit');
        Route::put('{wallpaper}', 'WallpaperController@update')->name('update');
        Route::delete('{wallpaper}', 'WallpaperController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'collection.', 'prefix' => 'collection' ], function () {
        Route::get('', 'CollectionController@index')->name('index');
        Route::get('create-collection', 'CollectionController@create')->name('create');
        Route::post('', 'CollectionController@store')->name('store');
        Route::get('{collection}/edit', 'CollectionController@edit')->name('edit');
        Route::put('{collection}', 'CollectionController@update')->name('update');
        Route::delete('{collection}', 'CollectionController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'tag.', 'prefix' => 'tag' ], function () {
        Route::get('', 'TagController@index')->name('index');
        Route::post('', 'TagController@store')->name('store');
        Route::get('{tag}/edit', 'TagController@edit')->name('edit');
        Route::put('{tag}', 'TagController@update')->name('update');
        Route::delete('{tag}', 'TagController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'category.', 'prefix' => 'category' ], function () {
        Route::get('', 'CategoryController@index')->name('index');
        Route::post('', 'CategoryController@store')->name('store');
        Route::get('{category}/edit', 'CategoryController@edit')->name('edit');
        Route::put('{category}', 'CategoryController@update')->name('update');
        Route::delete('{category}', 'CategoryController@destroy')->name('destroy');
    });

    Route::group([ 'as' => 'img.', 'prefix' => 'image' ], function () {
        Route::get('', 'ImgController@index')->name('index');
        Route::get('create-img', 'ImgController@create')->name('create');
        Route::post('', 'ImgController@store')->name('store');
        Route::get('{img}/edit', 'ImgController@edit')->name('edit');
        Route::put('{img}', 'ImgController@update')->name('update');
        Route::delete('{img}', 'ImgController@destroy')->name('destroy');
    });

});

app/Models/Wallpaper.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Model;

class Wallpaper extends Model
{
    protected $fillable = [
        'slug',
        'name',
        'is_primary',
        'is_published',
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = $value;

        if (!$this->exists) {
            $this->setUniqueSlug($value, '');
        }
    }

    protected function setUniqueSlug($name, $extra)
    {
        $slug = str_slug($name . '_' . $extra);

        if (static::whereSlug($slug)->exists()) {

            $this->setUniqueSlug($name, intval($extra) + 1);

            return;
        }

        $this->attributes['slug'] = $slug;
    }

    public function category()
    {
        return $this->belongsToMany(Category::class);
    }

    public function image()
    {
        return $this->morphOne(Image::class, 'imageable');
    }

}

app/Http/Controllers/WallpaperController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreWallpaper;
use App\Http\Requests\UpdateWallpaper;
use App\Models\Category;
use App\Models\Wallpaper;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class WallpaperController extends Controller
{
    public function index()
    {
        $wallpaper = Wallpaper::orderBy('id', 'ASC')->get();

        return view('backend.wallpaper.index', compact('wallpaper'));
    }

    public function create()
    {
        $categories = Category::all()->pluck('name','id');

        return view('backend.wallpaper.create',compact('categories'));
    }

    public function store(StoreWallpaper $request)
    {
        DB::transaction(function () use ($request) {
            $data = $request->data();

            $wallpaper = Wallpaper::create($data);
            foreach($request->category as $cat){
               $pivot = $wallpaper->category()->attach($cat);
            }
            $this->uploadRequestImage($request, $wallpaper);
        });

        return redirect()->route('wallpaper.index')->withSuccess(trans('Wallpaper has been added successfully', [ 'entity' => 'Wallpaper' ]));
    }

    public function edit(Wallpaper $wallpaper)
    {
        return view('backend.wallpaper.edit', compact('wallpaper'));
    }

    public function update(UpdateWallpaper $request, Wallpaper $wallpaper)
    {
        DB::transaction(function () use ($request, $wallpaper) {

            $data = $request->data();

            $wallpaper->update($data);

            if ($request->image)
            {
                $this->uploadRequestImage($request, $wallpaper);
            }
        });

        return redirect()->route('wallpaper.index')->with('success', 'Wallpaper has been updated', ['entity'=>'Wallpaper']);
    }


    public function destroy(Wallpaper $wallpaper)
    {
        $wallpaper->delete();

        return back()->with('success', 'wallpaper has been deleted');
    }
}

resources/views/backend/wallpaper/partials/form.blade.php
<div class="row">
    <div class="col-md-12">
    {{--<!-- @include('partials.errors') -->--}}
    </div>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-head">
                <header>{!! $header !!}</header>
                <div class="tools visible-xs">
                    <a class="btn btn-default btn-ink" href="{{ route('wallpaper.index') }}">
                        <i class="md md-arrow-back"></i>
                        Back
                    </a>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="Publish">
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                            {{ Form::text('name',old('name'),['class'=>'form-control', 'required']) }}
                            {{ Form::label('name','Name*') }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <label class="text-default-light">Featured Image</label>
                        @if(isset($wallpaper) && $wallpaper->image)
                            <input type="file" name="image" class="dropify" data-default-file="{{ asset($wallpaper->image->path) }}"/>
                        @else
                            <input type="file" name="image" class="dropify"/>
                        @endif
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <select class="form-control select2-list" name="category[]" multiple="multiple" id="wallpaper_category">
                                <option value="">Select Category</option>
                                @foreach($categories as $key => $category)
                                    <option value="{{$key}}"
                                            @if(isset($wallpaper->category_id) ? $wallpaper->category_id == $key : null) selected="selected" @endif>{{$category}}</option>
                                @endforeach
                            </select>
                            {{ Form::label('category', 'Category') }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-actionbar">
                <div class="card-actionbar-row">
                    <button type="reset" class="btn btn-default ink-reaction">Reset</button>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($wallpaper) && $wallpaper->is_published ? 'Save' : 'Publish' }}">
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card card-affix affix-4">
            <div class="card-head">
                <div class="tools">
                    <a class="btn btn-default btn-ink" href="{{ route('wallpaper.index') }}">
                        <i class="md md-arrow-back"></i>
                        Back
                    </a>
                </div>
            </div>
            <div class="card-actionbar">
                <div class="card-actionbar-row">
                    <button type="reset" class="btn btn-default ink-reaction">Reset</button>
                    <input type="submit" name="draft" class="btn btn-info ink-reaction" value="Save Draft">
                    <input type="submit" name="publish" class="btn btn-primary ink-reaction" value="{{ isset($wallpaper) && $wallpaper->is_published ? 'Save' : 'Publish' }}">
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script>
        $(document).ready(function () {
            $('#wallpaper_category').select2();
        })
    </script>
@endpush

resources/views/backend/wallpaper/partials/tables.blade.php
<tr>
    <td>{{++$key}}</td>
    <td>{{ str_limit($wallpaper->name, 47) }}</td>
    <td class="text-center">
        @if ($wallpaper->is_published == '1' )
            <span class="label label-success">{{ $wallpaper->is_published ? 'Yes' : 'No' }}</span>
        @elseif( $wallpaper->is_published  == '0' )
            <span class="label label-warning">{{ $wallpaper->is_published ? 'Yes' : 'No' }}</span>
        @endif
    </td>
    <td class="text-right">
        <button type="button" data-url="{{ route('wallpaper.destroy', $wallpaper->slug) }}" class="btn btn-flat btn-primary btn-xs item-delete">
            Delete
        </button>
        <a href="{{route('wallpaper.edit', $wallpaper->slug)}}" class="btn btn-flat btn-primary btn-xs">
            Edit
        </a>
    </td>
</tr>